### ISSUE TITLE
Unable to set any configurations

### ISSUE THREAD

**Issue by alelom** [timvink/mkdocs-git-revision-date-localized-plugin#103]
### Description

Using `git-revision-date-localized-plugin` along with "Material for Mkdocs". I was asked to raise this issue here as they do not believe it is related to Material: https://github.com/squidfunk/mkdocs-material/issues/4697#issuecomment-1332558500.

The plugin works when no settings are assigned in the `mkdocs.yml` file, i.e.:

```yml
plugins:
  - git-revision-date-localized
```

Shows correctly the last revision date in the webpages.

However, as soon as I add any custom setting, e.g.:

```yml
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
```

The build fails, and this error is returned:

```
ERROR    -  Config value 'plugins': Invalid Plugins configuration
Aborted with 1 Configuration Errors!
```

For me this happens consistently regardless of any other plugin/extension/custom css/etc.

Note that this happens even if you set a configuration to its own default value, e.g.:

```yml
plugins:
  - git-revision-date-localized:
      type: date
```

which may indicate an incorrect parsing of the configurations?

### Steps to reproduce

1. Install `git-revision-date-localized` via pip
2. Configure it in the yml file without any configuration
3. Build the website locally
4. Verify that it builds
5. Add any configuration to `git-revision-date-localized` in the yml file
6. Verify that build fails

### Package versions

- Python: 3.10.8
- MkDocs: 1.4.2 
- Material: 8.5.10 (I'm on Windows and running `grep` is not an option -- just noting it 😄)

### Configuration

```yaml
site_name: BHoM documentation
site_url: https://bhom.xyz/documentation/
repo_url: https://github.com/BHoM/documentation
edit_uri: edit/main/docs/

theme:
  name: material

plugins:
  - git-revision-date-localized: #uncommenting any of the lines below makes the build fail.
    # fallback_to_build_date: false
    # enable_creation_date: true
    # type: date
```

### System information

- Operating system: Windows 10
- Browser: Chrome

**Comment by timvink** [comment]
That's a strange one indeed. I cannot reproduce, using python 3.10 and same versions of plugin and mkdocs/mkdocs-material. 

Furthermore, I have a scheduled job so I can find any breaking changes in the dependencies, which hasn't been trigger. I retriggered the [builds on master branch](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/actions/runs/3619928428), but they are succeeding.

Windows support is always tricky though. My first thought was encoding, as windows uses different encodings for line ending (`\r\n` vs `\n`, see [link](https://medium.com/@csmunuku/windows-and-linux-eol-sequence-configure-vs-code-and-git-37be98ef71df)). 

Did you copy/paste those options from somewhere? Can you try manually typing them in your editor and then saving them? Or, you can use your editor to enforce consistent line endings.

The second thing I can think of is this has something to do with mkdocs 1.4, that introduced some changes around the configuration. Can you try again with `pip install mkdocs==1.3.1` ? If that works, I know where to start digging!

**Comment by timvink** [comment]
Had a chance to look at the suggestions yet?

**Comment by alelom** [comment]
> Did you copy/paste those options from somewhere? Can you try manually typing them in your editor and then saving them? Or, you can use your editor to enforce consistent line endings.

Did them manually, and tried several combinations. It's not a line endings issue I believe

> The second thing I can think of is this has something to do with mkdocs 1.4, that introduced some changes around the configuration. Can you try again with pip install mkdocs==1.3.1

trying that asap.

**Comment by alelom** [comment]
Build fails also on mkdocs v1.3.1 with same modality explained in the post.

**Comment by timvink** [comment]
Ok one more idea. I noticed you haven't defined any other options in any other plugins. It might be indentation.

Can you indent with one tab? Or try four spaces?
Can you try specifying any option of any other plugin (to confirm the problem is with this plugin). For example https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#options

I noticed that in the mkdocs of this repo I used double spaces for my options, maybe that doesn't work well in windows.

**Comment by alelom** [comment]
Hi, thanks for the messages. I did try with different indentations. I also have tried it in isolation and with other plugins that have options set. I will leave you my full `yml` config file, maybe you will spot if I'm doing anything wrong:

<details>

```yml

site_name: BHoM documentation
copyright: Copyright &copy; 2018 - 2022 BHoM
site_url: https://bhom.xyz/documentation/
repo_url: https://github.com/BHoM/documentation
edit_uri: edit/main/docs/

theme:
  name: material
  logo: _images/logos/logo.png
  favicon: _images/logos/favicon.ico
  palette:
    primary: white
    accent: pink

  features:
    - navigation.tracking
    - navigation.top

plugins:
  - search
  - awesome-pages # allows to customise the ordering of pages.
  - git-revision-date-localized: # Displays date created/modified on the page. The below configurations are bugged, so only date modified works.
    #enable_creation_date: true


markdown_extensions:
  - attr_list # allows to add HTML/CSS attributes to almost every Markdown element, useful for e.g. aligning an image to the left/right (can't do centre though! use md_in_html instead)
  - md_in_html # allows to add markdown within HTML elements, useful for e.g. adding image captions or centering an image
  
  - pymdownx.betterem # Wider support to markdown symbols
  
  # Code syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  # Mathjax support
  - pymdownx.arithmatex:
      generic: true

  # Call-outs and note boxes ('admonition')
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript: 
  # Also required for Mathjax support
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/BHoM
      name: BHoM on Github

```
</details>

**Comment by dcaddick** [comment]
Hi, I'm getting exactly the same error from this action:
[https://github.com/dcaddick/gsd_public/actions/runs/3937319131](url)
![image](https://user-images.githubusercontent.com/19640455/212846582-cfda2ea9-41bc-4c09-be3c-a1bb7d079b0f.png)

Installing this Plugin is fine, no prob at all.
But once it reaches the "enablement" phase of adding the hook by reading the mkdocs.yml file
Copy of my config from this file here: [https://github.com/dcaddick/gsd_public/blob/main/mkdocs.yml](url)

Once enabled as below, it will fail every time, if I comment out the Plugin it'll work fine

Relevant snip:

```
# Plugins
plugins:
  - search
  - simple
  #- git-authors:
  #      exclude:
  #          - index.md
  - git-revision-date-localized
  #    type: timeago
  #    timezone: Europe/Amsterdam
  #    locale: en
  #    fallback_to_build_date: false
  #    enable_creation_date: true
  #- glightbox
  #- social
  #- awesome-list
  #- table-reader
  #- img2fig
  #- mermaid2
  #- macros
  #- minify
```

**Comment by timvink** [comment]
@dcaddick your issue is another one. From your link I could deduce you are using https://github.com/athackst/mkdocs-simple-plugin. Please see their documentation on how to properly install plugins. Secondly, `mkdocs-simple-plugin` does not document which plugins are not supported. Because it copies all content to a `/tmp` directory, but does not copy the `.git` folder, all git-based plugins will not work. Please find more information in the issue: https://github.com/athackst/mkdocs-simple-plugin/issues/466

@alelom I will need to setup a development environment on a windows machine to be able to try and reproduce the error. Not a high priority for me tbh..

**Comment by dcaddick** [comment]
Thanks Tim,

Any suggestions on a better alternative that does fully support the git elements?

Regards,
DaveC

**Comment by alelom** [comment]
Thanks @timvink, that's understandable. I will update you in case I find something else. For example, since you are suggesting that this is an OS-specific issue, I will try and set the configuration to include these settings and see if at least the github actions are still able to run it correctly, given they run on Linux.

**Comment by christophhillisch** [comment]
I am also running into the problem that configurations beyond the first one (`show_contribution: true`) are ignored. I set `authorship_threshold_percent: 10`, but I found contributions of 0.88 %.

Package Versions:

- mkdocs 1.4.2
- mkdocs-git-authors-plugin 0.7.0 
- mkdocs-git-revision-date-localized-plugin 1.1.0 
- mkdocs-material 9.0.13 
- mkdocs-material-extensions 1.1.1 
- python 1.10

**Comment by timvink** [comment]
Closing the issue as I can't reproduce

**Comment by opeyemitechpro** [comment]
> git-revision-date-localized

Both my creation date and last build date always resets to last build date for all doc pages when I push to my repo.
I'm hosting on github, how can I solve this?


Here is how I have also set my portion of mkdocs.yml 

```
  - git-revision-date-localized:
      type: timeago
      locale: en
      enable_creation_date: true
      fallback_to_build_date: true

```
