### ISSUE TITLE
Feature request: exclude specific commits when calculating the 'last update' calculation

### ISSUE THREAD

**Issue by markszabo** [timvink/mkdocs-git-revision-date-localized-plugin#113]
In our usage it sometimes happens that we need to make changes to many/all markdown files at once, e.g. running a formatter, or when the name of an internal product or team changes. We would like to exclude these changes from the 'last update' calculation, as they don't mean that the content was actually checked and actualized (but merely that someone run a search and replace over the entire repo). This doesn't happen that often, so we have a limited number of these commits (less than 5).

Thus I'd like to propose a new config option called `exclude_commits` as a list of commit ids that should not be considered when calculating the last update time, e.g.

```yaml
plugins:
  - git-revision-date-localized:
      exclude_commits:
          - 6150fad
          - 7d89e01
          - e7f82de
```

If this sounds like something you would accept to be part of the plugin, I'm happy to send a PR with the implementation and doc update.
