### ISSUE TITLE
Create date not correct on Github pages

### ISSUE THREAD

**Issue by mendax1234** [timvink/mkdocs-git-revision-date-localized-plugin#118]
Hi, I am trying to use this plugin on my mkdocs material site. When l am doing the local test, l find that everything is Ok. But after l push my changes to the GitHub, and see my website online. I find that the creation date is wrong, it will always be the date l have the last commit on the post. 

This is all my mkdocs material plugin config:
```
plugins:
  - blog
  - search
  - git-revision-date-localized:
      enable_creation_date: true
```

Since in the local test environment, everything is good. So, l wonder if that problem lies in the `.git` folder. Since it isn't uploaded to the cloud on Github. But l think Github should have its own .git folder to store the changes of the file. l am so confused about this problem.

Thanks so much!
