### ISSUE TITLE
'last_update' in PDF version not working

### ISSUE THREAD

**Issue by timvink** [timvink/mkdocs-git-revision-date-localized-plugin#12]
When building PDF versions of the website, the last updated date does not display.  

![image](https://user-images.githubusercontent.com/5570380/74941620-a2b2b300-53f3-11ea-9e76-593f55032ee9.png)

Perhaps we can hide it somehow when printing PDF.

**Comment by RDIL** [comment]
The link attribute has something to do with this, maybe put CSS with display none through that.

**Comment by timvink** [comment]
When using this plugin with `mkdocs-material`, the last date is wrapped in a div with class `md-source-date`. We can prevent displaying the last revision date when printing by adding some extra CSS when building:

```css
@media print {
    .md-source-date { display: none; }
}
```

Just tested this and it works nicely with [mkdocs-pdf-export-plugin](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin)

Good to be explicit to users about this, and add an option `enable_on_printing` with a default of `false`.

We would also need to wrap output with `<span class="git-revision-date-localized">` `</span>`, so we can also accomodate for use cases without mkdocs-material. CSS to add is then:

```css
@media print {
    .md-source-date { display: none; }
    .git-revision-date-localized { display: none; }
}
```
