### ISSUE TITLE
Whitelist / Negate certain excludes with a `!`?

### ISSUE THREAD

**Issue by hudsonm62** [timvink/mkdocs-git-revision-date-localized-plugin#130]
I'm excluding all my `index.md` files (as these are for the most part "home" pages), however there's one or two I want to keep the dates on. 

Sometimes, you can just prefix `!` to "negate" or "ignore" a file or pattern (like in a [.gitignore](https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository#_ignoring) for example). But doesn't seem to work here (assuming it's because it relies on glob??)

```yaml
  - git-revision-date-localized:
      exclude:
        - "!topics/index.md" # don't exclude topics page
        # ignore all homepages
        - "index.md"
        - "**/index.md"

```

Not sure if this is possible already and I'm just going about it the wrong way? but would be great if I could negate certain patterns/specific files from the `exclude`.
