### ISSUE TITLE
Formatted date is not localized

### ISSUE THREAD

**Issue by Guts** [timvink/mkdocs-git-revision-date-localized-plugin#21]
## Reproduce

Lets' use the [fixtures used in tests](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/4e36cbee97dce3895f1e6e272fb5b65efa1f32b2/tests/basic_setup/mkdocs_locale.yml), just moving from `nl` to `fr` to see more obvious difference:

1. set locale in config:

```yaml
site_name: test gitrevisiondatelocalized_plugin
use_directory_urls: true

locale: fr

plugins:
    - search
    - git-revision-date-localized
```

2. Serve site : `mkdocs serve -f .\tests\basic_setup\mkdocs_locale.yml`
3. Date is not localized:

![image](https://user-images.githubusercontent.com/1596222/77743639-ab149400-7018-11ea-8f25-bf41b155af1c.png)

## Expected result

![image](https://user-images.githubusercontent.com/1596222/77743734-ced7da00-7018-11ea-820b-8e888bab5b2f.png)

## Debug

The error is located in this line:

https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/blob/2f8dc73ffc033d68e310441f0f8fc79ba27e6858/mkdocs_git_revision_date_localized_plugin/util.py#L81

Should pass the inherited `locale`:

```python
return self._date_formats(unix_timestamp=unix_timestamp, locale=locale)
```
