### ISSUE TITLE
Add dark mode to docs

### ISSUE THREAD

**Issue by timvink** [timvink/mkdocs-git-revision-date-localized-plugin#68]
```
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: blue
          accent: blue
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: blue
          accent: blue
```
